name: finalapp
description: Google Flutter course homework.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  pedantic: any
  audioplayers: ^0.17.0
  http: any
  auto_size_text: any
  built_value: any
  built_collection: any
  redux: any
  flutter_redux: any
  freezed_annotation: ^0.12.0

  redux_epics: ^0.14.0
  rxdart: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  built_value_generator: any
  freezed: any
  analyzer: any

flutter:

  uses-material-design: true
